<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="HabloTruckPlatform.Domain">
      <HintPath>..\HabloTruckPlatform.Domain\bin\Debug\net10.0\HabloTruckPlatform.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
